/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package stackAndQueue;
//
//public class App {
//
//    public static void main(String[] args) {

//      BracketValidation bracketValidation = new BracketValidation();
//      System.out.println(bracketValidation.validateBrackets("{}"));
//      System.out.println(bracketValidation.validateBrackets("{}(){}"));
//      System.out.println(bracketValidation.validateBrackets("()[[Extra Characters]]"));
//      System.out.println(bracketValidation.validateBrackets("(){}[[]]"));
//      System.out.println(bracketValidation.validateBrackets("(){}[[]]"));
//      System.out.println(bracketValidation.validateBrackets("{}{Code}[Fellows](())"));
//      System.out.println(bracketValidation.validateBrackets("[({}]"));
//      System.out.println(bracketValidation.validateBrackets("(]("));
//      System.out.println(bracketValidation.validateBrackets("{(})"));

//      AnimalShelter shelter = new AnimalShelter();
//
//      shelter.enqueue(new Cat("cat1"));
//      shelter.enqueue(new Dog("dog1"));
//      shelter.enqueue(new Cat("cat2"));
//      shelter.enqueue(new Dog("dog2"));
//
//      System.out.println(shelter.dequeue("cat"));
//      System.out.println(shelter.dequeue("cAt"));
//      System.out.println(shelter.dequeue("doG"));
//      System.out.println(shelter.dequeue("bird"));
//      shelter.getCats();
//      shelter.getDogs();
//      Stack<java.io.Serializable> stack = new Stack<>();
////
//      stack.push(3);
//      stack.push(8);
//      stack.push(14);
//      stack.push(0);
////
//      Double h = Double.POSITIVE_INFINITY;
//      System.out.println(h);
//      stack.toString();
//      stack.pop();
//      stack.pop();
//      stack.toString();
//      System.out.println(stack.maxNum);
//
//      System.out.println(stack.pop());
//      System.out.println(stack.pop());
//      stack.toString();
//      System.out.println(stack.peek());
//      System.out.println(stack.pop());
//
//      System.out.println("<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
//
//      Queue<java.io.Serializable> queue = new Queue<>();

//      queue.enqueue(8);
//      queue.enqueue(4);
//      queue.enqueue(7);
//      queue.enqueue(6);
//      queue.toString();
//
//      System.out.println(queue.dequeue());
//      queue.toString();
//      System.out.println(queue.dequeue());
//      queue.toString();
//      System.out.println("peek "+queue.peek());
//      System.out.println(queue.dequeue());
//      queue.toString();
//      System.out.println(queue.dequeue());
//      queue.toString();
//      System.out.println(queue.dequeue());
//      queue.toString();
//      System.out.println("<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
//      PseudoQueue<java.io.Serializable> pseudoQueue = new PseudoQueue<>();
//
//      pseudoQueue.enqueue(3);
//      pseudoQueue.enqueue(4);
//      pseudoQueue.enqueue(9);
//      pseudoQueue.enqueue(90);

//      pseudoQueue.toStringStack1();

//      System.out.println(pseudoQueue.dequeue());
//      System.out.println(pseudoQueue.dequeue());
//      System.out.println(pseudoQueue.dequeue());
//      System.out.println(pseudoQueue.dequeue());
//      System.out.println(pseudoQueue.dequeue());
//      pseudoQueue.toStringStack2();
//    }
//}
